2.4. Problem Statement: STATISTICS 4

In [ ]:
Problem Statement 1:
Is gender independent of education level? A random sample of 395 people were surveyed and each person was asked to report the highest education level they obtained.The data that resulted from the survey is summarized in the following table:

           High School Bachelors Masters Ph.d.     Total
#Female      60         54       46      41        201
#Male        40         44       53      57        194
#Total      100         98       99      98        395

#Question: Are gender and education level dependent at 5% level of significance? 
In other words, given the data collected above,
Is there a relationship between the gender of an individual and the level of education that they have obtained?

In [ ]:
Solution:
    
Step 1: Determine the formula:   
            Null Hypothesis: The two categorical variables are independent.
            Alternative Hypothesis: The two categorical variables are dependent.
        The chi-square test statistic is calculated by using the formula:
            χ2 = ∑(O−E)^2/E
where, 
O represents the observed frequency
E represents the expected frequency under the null hypothesis and computed by:
        E = (row total × column total) / sample size
We will compare the value of the test statistic to the critical value of χ2α with degree of freedom = (r - 1) (c - 1), 
and reject the null hypothesis if χ2>χ2α.

Step 2: Determine the table of expected counts:
        eg) High School Female = (201*100)/395 = 50.886 (we shall get the table as below for rest of the values once calculated)      
               
          High School  Bachelors  Masters   Ph.d.   Total
Female       50.886     49.868    50.377   49.868    201
Male         49.114     48.132    48.623   48.132    194
Total          100        98        99       98      395

Step 3: Calculate the Chi-Square value:         
        
        χ2= (60−50.886)^2/50.886 + (54−49.868)^2/49.868 + (46−50.377)^2/50.377 + (41-49.868)^2/49.868 + (54−49.868)^2/49.868 + (40-49.114)^2/49.114 + (44-48.132)^2/48.132 + (53-48.623)^2/48.623 + (57−48.132)^2/48.132 = 8.006
        χ2= 8.006
         
Step 4: Conclusion:
        The critical value of χ2 with 3 degree of freedom is 7.815
        Since 8.006 > 7.815, therefore we reject the null hypothesis
        Therefore, the education level depends on gender at a 5% level of significance.

Problem Statement 2:
Using the following data, perform a one-way analysis of variance using α=.05. Write up the results in APA format.
[Group1: 51, 45, 33, 45, 67]
[Group2: 23, 43, 23, 43, 45]
[Group3: 56, 76, 74, 87, 56]

In [ ]:
1)Sample means of each groups 

Group 1)(51+45+33+45+67)/5=48.20
Group 2)(23+43+23+43+45)/5=35.4
Group 3)(56+76+74+87+56)/5=69.8

2)Calcualting within group variance of group 1.

  value mean deviations square deviations
1    51 48.2        2.8          7.84
2    45 48.2       -3.2         10.24
3    33 48.2      -15.2        231.04
4    45 48.2       -3.2         10.24
5    67 48.2       18.8        353.44

3)Calcualting within group variance of group 2.

  value mean deviations square deviations
1    23 35.4      -12.4        153.76
2    43 35.4        7.6         57.76
3    23 35.4      -12.4        153.76
4    43 35.4        7.6         57.76
5    45 35.4        9.6         92.16

4)Calcualting within group variance of group 3.

  value mean deviations square deviations
1    56 69.8      -13.8        190.44
2    76 69.8        6.2         38.44
3    74 69.8        4.2         17.64
4    87 69.8       17.2        295.84
5    56 69.8      -13.8        190.44

5)Calculation MSerror(average within group variance)
612.8,515.2,732.8

Var1=612.8/(5−1)=153.2

Var2=515.2/(5−1)=128.8

Var3=732.8/(5−1)=183.2

MSerror=(153.2+128.8+183.2)/3=155.07(the average within-group variance)

8)Calculating the remaining error (or within) terms for the ANOVA table:

dferror=15−3=12(The degrees of freedom for the Total SS is n=N - 1 = 15 – 1 = 14.We have k(3)(k -1=2) treatment levels.So 14 -2=12)

SSerror=(155.07)(15−3)=1860.8

9)
Calculation value of MSbetween:

grand mean=48.2+35.4+69.8/3=51.13

 group mean grand mean deviations sq deviations
       48.2      51.13      -2.93          8.58
       35.4      51.13     -15.73        247.43
       69.8      51.13      18.67        348.57

Sum of squares (SSmeans)=604.58

Varmeans=604.583−1=302.29

MSbetween=(302.29)(5)=1511.45(This method of estimating the variance IS sensitive to group mean differences!)


10)Calculating the remaining between (or group) terms of the ANOVA table:

dfgroups=3−1=2

SSgroup=(1511.45)(3−1)=3022.9

Test statistic and critical value

F=1511.45/155.07=9.75

Fcritical=F(2,12)=3.89

Decision: reject H0 (F > Fcritical)

11)
ANOVA table:

source 	SS 	df 	MS 		F
group 	3022.9 	2 	1511.45 	9.75
error 	1860.8 	12 	155.07 	
total 	4883.7 			

Effect size

η2=3022.9/4883.7 =0.62

12)
APA writeup
F(2, 12)=9.75, p <0.05, η2=0.62.

Problem Statement 3:
Calculate F Test for given 10, 20, 30, 40, 50 and 5,10,15, 20, 25.
For 10, 20, 30, 40, 50:
Solution:

In [ ]:
Step 1: Calculate Variance of first set 
Total Inputs (N) =(10,20,30,40,50) 
Total Inputs (N) = 5 
Mean (xm)= (x1+x1+x2...xn)/N 
Mean (xm)= 150/5 = 30
SD=sqrt(1/(N-1)*((x1-xm)^2+(x2-xm)^2+..+(xn-xm)^2)) 
=sqrt(1/(5-1)((10-30)^2+(20-30)^2+(30-30)^2+(40-30)^2+(50-30)^2)) 
=sqrt(1/4((-20)^2+(-10)^2+(0)^2+(10)^2+(20)^2)) 
=sqrt(1/4((400)+(100)+(0)+(100)+(400))) 
=sqrt(250) = 5.8114 
Variance=SD^2 
Variance=15.8114^2 = 250 

Step 2: Calculate Variance of second set 
Total Inputs(N) =(5,10,15,20,25) 
Total Inputs(N) = 5 
Mean (xm)= (x1+x2+x3...xN) / N 
Mean (xm)= 75/5 = 15
SD=sqrt(1/(N-1)*((x1-xm)^2+(x2-xm)^2+..+(xn-xm)^2)) 
=sqrt(1/(5-1)((5-15)^2+(10-15)^2+(15-15)^2+(20-15)^2+(25-15)^2)) 
=sqrt(1/4((-10)^2+(-5)^2+(0)^2+(5)^2+(10)^2)) 
=sqrt(1/4((100)+(25)+(0)+(25)+(100))) 
=sqrt(62.5) = 7.9057 
Variance=SD^ 2 
Variance=7.90572 = 62.5 

Step 3: Calculate F Test value
F Test = (variance of 10, 20,30,40,50) / (variance of 5, 10, 15, 20, 25) 
= 250/62.5 = 4
Therefore the F Test value is 4